config/routes.rb
Rails.application.routes.draw do
  root 'page#index'

    get '/secret' => 'page#secret'

    get '/register' => 'users#new'
    resources :users

    # These routes will be for showing a login form, logging in, and logging out
    get '/login' => 'sessions#new'
    post '/login' => 'sessions#create'
    get '/logout' => 'sessions#destroy'

    get '/equipment' => 'equipment#select'
    post '/assign_equipment' => 'equipment#assign_equipment'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/equipment.rb
class Equipment < ApplicationRecord
  has_and_belongs_to_many :users
  has_and_belongs_to_many :excerises

  scope :find_by_name, -> (name){find_by(name: name.to_s)}


  def assign_to_user(user,equip_hash)
    equip_hash.each do |name,state|
      user.equipment << Equipment.find_by_name(name) if state == '1'
    end
  end

end

app/models/exercise.rb
class Exercise < ApplicationRecord
  has_and_belongs_to_many :equipment
  has_and_belongs_to_many :routines
  has_and_belongs_to_many :muscle_groups
end

app/models/muscle_group.rb
class MuscleGroup < ApplicationRecord
  has_and_belongs_to_many :exercises
end

app/models/routine.rb
class Routine < ApplicationRecord
  has_and_belongs_to_many :exercises

  def self.build_routine
    routine = []

    routine << Exercise.where(difficulty: 3).select do |d|
      d.muscle_groups.any?{|mg| mg.name == 'warmup'}
    end.sample(2)
    p routine.last

    routine << Exercise.where(difficulty: 2).select do |d|
      d.muscle_groups.any?{|mg| mg.name == 'legs'} && d.muscle_groups.any?{|mg| mg.name == 'shoulders'}
    end.sample(2)
    p routine.last


    routine << Exercise.where(difficulty: 1).select do |d|
      d.muscle_groups.any?{|mg| mg.name == 'legs'} && d.muscle_groups.any?{|mg| mg.name == 'shoulders'}
    end.sample
    p routine.last


    routine <<  Exercise.where(difficulty: 3).select do |d|
      d.muscle_groups.any?{|mg| mg.name == 'legs'}
    end.sample
    p routine.last


    routine << Exercise.where(difficulty: 2).select do |d|
      d.muscle_groups.any?{|mg| mg.name == 'legs'} && d.muscle_groups.any?{|mg| mg.name == 'shoulders'}
    end.sample(2)
    p routine.last

    routine << Exercise.where(difficulty: 1).select do |d|
      d.muscle_groups.any?{|mg| mg.name == 'legs'} && d.muscle_groups.any?{|mg| mg.name == 'shoulders'}
    end.sample
    p routine.last

    routine << Exercise.where(difficulty: 3).select do |d|
      d.muscle_groups.any?{|mg| mg.name == 'legs'}
    end.sample

    routine << Exercise.where(difficulty: 2).select do |d|
      d.muscle_groups.any?{|mg| mg.name == 'legs'}
    end.sample

    routine << Exercise.where(difficulty: 1).select do |d|
      d.muscle_groups.any?{|mg| mg.name == 'legs'}
    end.sample(2)

    routine
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_and_belongs_to_many :equipment
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def current_user
    # session[:user_id] = nil
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user
end

app/controllers/equipment_controller.rb
class EquipmentController < ApplicationController

  def index
    @equipment = Equipment.all
  end

  def new
    @equipment = current_user.equipment.build
  end

  # def show
  #   if current_user.something ==
  # end

  def select
    @equipment = Equipment.all
  end

  def assign_equipment
    Equipment.assign_to_user(current_user,equipment_params)
    redirect_to root_path
  end

  def create
    @equipment = Equipment.new
  end

  def equipment_params
    params.require(:equipment)
  end

end

app/controllers/exercises_controller.rb
class ExercisesController < ApplicationController
end

app/controllers/muscle_groups_controller.rb
class MuscleGroupsController < ApplicationController
end

app/controllers/page_controller.rb
class PageController < ApplicationController
  def index
     redirect_to register_path if session[:user_id].nil?
  end

  def secret
    redirect_to root_path unless current_user.admin?
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by_email(params[:email])
# If the user exists AND the password entered is correct.
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to @user
    else
      # If user's login doesn't work, send them back to the login form.
      redirect_to login_path
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to login_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

    # GET /users
    # GET /users.json
    def index
      @users = User.all
    end
    def show_routine
      @routines = build_routine
    end
    # GET /users/1
    # GET /users/1.json
    def show
    end

    # GET /users/new
    def new
      @user = User.new
    end

    # GET /users/1/edit
    def edit
    end

    # POST /users
    # POST /users.json
    def create
      @user = User.new(user_params)

      if @user.save
        session[:user_id] = @user.id
        redirect_to root_path
      else
        redirect_to register_path
      end
    end

    # PATCH/PUT /users/1
    # PATCH/PUT /users/1.json
    def update
      respond_to do |format|
        if @user.update(user_params)
          format.html { redirect_to @user, notice: 'User was successfully updated.' }
          format.json { render :show, status: :ok, location: @user }
        else
          format.html { render :edit }
          format.json { render json: @user.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /users/1
    # DELETE /users/1.json
    def destroy
      @user.destroy
      respond_to do |format|
        format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
        format.json { head :no_content }
      end
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_user
        @user = User.find(params[:id])
      end

      # Never trust parameters from the scary internet, only allow the white list through.
      def user_params
        params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, {equipment_ids: []})
      end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/equipment_helper.rb
module EquipmentHelper
end

app/helpers/exercises_helper.rb
module ExercisesHelper
end

app/helpers/muscle_groups_helper.rb
module MuscleGroupsHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/equipment/index.html.erb
<%= @equipment.all %>

app/views/equipment/new.html.erb
<%= form_for(equipment, remote: true) do |f| %>
  <% if equipment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(equipment.errors.count, "error") %> prohibited this equipment  from being saved:</h2>

      <ul>
      <% equipment .errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/equipment/select.html.erb
<%= form_for @user do |f| %>
  <%# @equipment.each do |e| %>
    <%#= check_box_tag(e.name.to_sym) %>
    <%#= label_tag(e.name.to_sym) %>
    <br>
    <%# end %>
  <%= f.submit%>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<!-- added these lines -->
<% if current_user %>
  Signed in as <%= current_user.first_name %> | <%= link_to "Logout", logout_path %>
<% else %>
  <%= link_to 'Login', login_path %> | <%= link_to 'Register', register_path %>
<% end %>

<%= yield %>

</body>
</html>

app/views/page/secret.html.erb
<h1>Secret</h1>

app/views/users/_form.html.erb
<%= form_for(user) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %>
    <%= f.text_field :first_name %>
  </div>

  <div class="field">
    <%= f.label :last_name %>
    <%= f.text_field :last_name %>
  </div>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>

  <!-- <div class="field">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div> -->

  <%= f.collection_check_boxes :equipment_ids, Equipment.all, :id, :name %> 

  <div class="actions">
    <%= f.submit 'Register' %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.first_name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>Register</h1>

<%= render 'form', user: @user %>
<!-- Changed the link tag below. -->
<%= link_to 'Log In', login_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.first_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

<h1><%= @routines %></h1>